In [10]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"D:\Mtech Sem 1\ITC lab\TOR_database\Scenario-A\SelectedFeatures-10s-TOR-NonTOR.csv")
df.head()

Source IP   Source Port  Destination IP   Destination Port   Protocol  \
0  10.0.2.15         53913   216.58.208.46                 80          6   
1  10.0.2.15         53913   216.58.208.46                 80          6   
2  10.0.2.15         53913   216.58.208.46                 80          6   
3  10.0.2.15         53913   216.58.208.46                 80          6   
4  10.0.2.15         53913   216.58.208.46                 80          6   

    Flow Duration   Flow Bytes/s   Flow Packets/s   Flow IAT Mean  \
0             435            0.0      4597.701149           435.0   
1             259            0.0      7722.007722           259.0   
2             891            0.0      2244.668911           891.0   
3            1074            0.0      1862.197393          1074.0   
4             315            0.0      6349.206349           315.0   

    Flow IAT Std  ...   Bwd IAT Min  Active Mean   Active Std   Active Max  \
0            0.0  ...             0            0            0            0   
1            0.0  ...             0            0            0            0   
2            0.0  ...             0            0            0            0   
3            0.0  ...             0            0            0            0   
4            0.0  ...             0            0            0            0   

    Active Min  Idle Mean   Idle Std   Idle Max   Idle Min   label  
0            0          0          0          0          0  nonTOR  
1            0          0          0          0          0  nonTOR  
2            0          0          0          0          0  nonTOR  
3            0          0          0          0          0  nonTOR  
4            0          0          0          0          0  nonTOR  

[5 rows x 29 columns]

In [11]:
df.describe()

Source Port   Destination Port      Protocol   Flow Duration  \
count  67834.000000       67834.000000  67834.000000    6.783400e+04   
mean   37912.753324       11566.395967     12.167291    2.991884e+06   
std    20986.077326       18374.765123      5.459410    4.063005e+06   
min       21.000000          21.000000      6.000000    0.000000e+00   
25%    19305.000000         137.000000      6.000000    4.435975e+04   
50%    43677.000000         443.000000     17.000000    4.108570e+05   
75%    54685.000000       16311.000000     17.000000    7.325550e+06   
max    65534.000000       65514.000000     17.000000    1.000000e+07   

        Flow Bytes/s   Flow Packets/s   Flow IAT Mean   Flow IAT Std  \
count   6.783200e+04     6.783400e+04    6.783400e+04   6.783400e+04   
mean             inf              inf    3.155927e+05   2.209662e+05   
std              NaN              NaN    6.988069e+05   6.409506e+05   
min     0.000000e+00     2.002581e-01    0.000000e+00   0.000000e+00   
25%     1.046553e+02     4.861712e+00    9.951270e+03   0.000000e+00   
50%     1.331365e+03     1.631734e+01    8.344079e+04   0.000000e+00   
75%     2.170103e+04     1.007038e+02    4.106090e+05   5.790789e+04   
max              inf              inf    9.987113e+06   7.045491e+06   

        Flow IAT Max   Flow IAT Min  ...   Bwd IAT Max   Bwd IAT Min  \
count   6.783400e+04   6.783400e+04  ...  6.783400e+04  6.783400e+04   
mean    8.983857e+05   1.924432e+05  ...  4.760216e+05  5.158576e+04   
std     1.738476e+06   5.780313e+05  ...  1.409648e+06  4.873526e+05   
min     0.000000e+00  -2.255000e+03  ...  0.000000e+00 -3.270000e+02   
25%     2.892575e+04   2.600000e+01  ...  0.000000e+00  0.000000e+00   
50%     1.786225e+05   1.371500e+03  ...  0.000000e+00  0.000000e+00   
75%     4.641098e+05   2.075310e+05  ...  8.278800e+04  1.700000e+01   
max     9.998126e+06   9.987113e+06  ...  9.996903e+06  9.996903e+06   

        Active Mean   Active Std    Active Max    Active Min     Idle Mean  \
count  6.783400e+04      67834.0  6.783400e+04  6.783400e+04  6.783400e+04   
mean   3.887655e+04          0.0  3.887655e+04  3.887655e+04  3.085054e+05   
std    3.154634e+05          0.0  3.154634e+05  3.154634e+05  1.453953e+06   
min    0.000000e+00          0.0  0.000000e+00  0.000000e+00  0.000000e+00   
25%    0.000000e+00          0.0  0.000000e+00  0.000000e+00  0.000000e+00   
50%    0.000000e+00          0.0  0.000000e+00  0.000000e+00  0.000000e+00   
75%    0.000000e+00          0.0  0.000000e+00  0.000000e+00  0.000000e+00   
max    4.999893e+06          0.0  4.999893e+06  4.999893e+06  9.998126e+06   

        Idle Std      Idle Max      Idle Min  
count    67834.0  6.783400e+04  6.783400e+04  
mean         0.0  3.085054e+05  3.085054e+05  
std          0.0  1.453953e+06  1.453953e+06  
min          0.0  0.000000e+00  0.000000e+00  
25%          0.0  0.000000e+00  0.000000e+00  
50%          0.0  0.000000e+00  0.000000e+00  
75%          0.0  0.000000e+00  0.000000e+00  
max          0.0  9.998126e+06  9.998126e+06  

[8 rows x 26 columns]

In [12]:
df.replace('Infinity', -1, inplace=True)
df["label"] = df["label"].map({"nonTOR": 0, "TOR": 1})
df["Source IP"] = df["Source IP"].apply(lambda x: float(x.replace(".", "")))
df[" Destination IP"] = df[" Destination IP"].apply(lambda x: float(x.replace(".", "")))

In [13]:
df.describe()

Source IP   Source Port   Destination IP   Destination Port  \
count  6.783400e+04  67834.000000     6.783400e+04       67834.000000   
mean   4.164971e+10  37912.753324     2.877324e+10       11566.395967   
std    5.842568e+10  20986.077326     5.620241e+10       18374.765123   
min    1.080600e+04     21.000000     8.888000e+03          21.000000   
25%    1.088130e+06  19305.000000     2.240025e+07         137.000000   
50%    1.985220e+09  43677.000000     1.312022e+09         443.000000   
75%    1.312022e+11  54685.000000     1.951541e+10       16311.000000   
max    2.221072e+11  65534.000000     2.552553e+11       65514.000000   

           Protocol   Flow Duration   Flow Bytes/s   Flow Packets/s  \
count  67834.000000    6.783400e+04   6.783200e+04     6.783400e+04   
mean      12.167291    2.991884e+06            inf              inf   
std        5.459410    4.063005e+06            NaN              NaN   
min        6.000000    0.000000e+00   0.000000e+00     2.002581e-01   
25%        6.000000    4.435975e+04   1.046553e+02     4.861712e+00   
50%       17.000000    4.108570e+05   1.331365e+03     1.631734e+01   
75%       17.000000    7.325550e+06   2.170103e+04     1.007038e+02   
max       17.000000    1.000000e+07            inf              inf   

        Flow IAT Mean   Flow IAT Std  ...   Bwd IAT Min   Active Mean  \
count    6.783400e+04   6.783400e+04  ...  6.783400e+04  6.783400e+04   
mean     3.155927e+05   2.209662e+05  ...  5.158576e+04  3.887655e+04   
std      6.988069e+05   6.409506e+05  ...  4.873526e+05  3.154634e+05   
min      0.000000e+00   0.000000e+00  ... -3.270000e+02  0.000000e+00   
25%      9.951270e+03   0.000000e+00  ...  0.000000e+00  0.000000e+00   
50%      8.344079e+04   0.000000e+00  ...  0.000000e+00  0.000000e+00   
75%      4.106090e+05   5.790789e+04  ...  1.700000e+01  0.000000e+00   
max      9.987113e+06   7.045491e+06  ...  9.996903e+06  4.999893e+06   

        Active Std    Active Max    Active Min     Idle Mean   Idle Std  \
count      67834.0  6.783400e+04  6.783400e+04  6.783400e+04    67834.0   
mean           0.0  3.887655e+04  3.887655e+04  3.085054e+05        0.0   
std            0.0  3.154634e+05  3.154634e+05  1.453953e+06        0.0   
min            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
25%            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
50%            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
75%            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
max            0.0  4.999893e+06  4.999893e+06  9.998126e+06        0.0   

           Idle Max      Idle Min         label  
count  6.783400e+04  6.783400e+04  67834.000000  
mean   3.085054e+05  3.085054e+05      0.118584  
std    1.453953e+06  1.453953e+06      0.323300  
min    0.000000e+00  0.000000e+00      0.000000  
25%    0.000000e+00  0.000000e+00      0.000000  
50%    0.000000e+00  0.000000e+00      0.000000  
75%    0.000000e+00  0.000000e+00      0.000000  
max    9.998126e+06  9.998126e+06      1.000000  

[8 rows x 29 columns]

In [14]:
# Remove infinity and null
df.replace([np.inf, -np.inf],np.nan, inplace=True)
# 2) use dropna
df.dropna(how='any',axis=0)
df.describe()


Source IP   Source Port   Destination IP   Destination Port  \
count  6.783400e+04  67834.000000     6.783400e+04       67834.000000   
mean   4.164971e+10  37912.753324     2.877324e+10       11566.395967   
std    5.842568e+10  20986.077326     5.620241e+10       18374.765123   
min    1.080600e+04     21.000000     8.888000e+03          21.000000   
25%    1.088130e+06  19305.000000     2.240025e+07         137.000000   
50%    1.985220e+09  43677.000000     1.312022e+09         443.000000   
75%    1.312022e+11  54685.000000     1.951541e+10       16311.000000   
max    2.221072e+11  65534.000000     2.552553e+11       65514.000000   

           Protocol   Flow Duration   Flow Bytes/s   Flow Packets/s  \
count  67834.000000    6.783400e+04   6.782800e+04     6.782800e+04   
mean      12.167291    2.991884e+06   2.535255e+05     3.304669e+03   
std        5.459410    4.063005e+06   5.624429e+06     4.955965e+04   
min        6.000000    0.000000e+00   0.000000e+00     2.002581e-01   
25%        6.000000    4.435975e+04   1.046553e+02     4.861706e+00   
50%       17.000000    4.108570e+05   1.331268e+03     1.631514e+01   
75%       17.000000    7.325550e+06   2.168678e+04     1.007034e+02   
max       17.000000    1.000000e+07   6.000000e+08     3.000000e+06   

        Flow IAT Mean   Flow IAT Std  ...   Bwd IAT Min   Active Mean  \
count    6.783400e+04   6.783400e+04  ...  6.783400e+04  6.783400e+04   
mean     3.155927e+05   2.209662e+05  ...  5.158576e+04  3.887655e+04   
std      6.988069e+05   6.409506e+05  ...  4.873526e+05  3.154634e+05   
min      0.000000e+00   0.000000e+00  ... -3.270000e+02  0.000000e+00   
25%      9.951270e+03   0.000000e+00  ...  0.000000e+00  0.000000e+00   
50%      8.344079e+04   0.000000e+00  ...  0.000000e+00  0.000000e+00   
75%      4.106090e+05   5.790789e+04  ...  1.700000e+01  0.000000e+00   
max      9.987113e+06   7.045491e+06  ...  9.996903e+06  4.999893e+06   

        Active Std    Active Max    Active Min     Idle Mean   Idle Std  \
count      67834.0  6.783400e+04  6.783400e+04  6.783400e+04    67834.0   
mean           0.0  3.887655e+04  3.887655e+04  3.085054e+05        0.0   
std            0.0  3.154634e+05  3.154634e+05  1.453953e+06        0.0   
min            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
25%            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
50%            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
75%            0.0  0.000000e+00  0.000000e+00  0.000000e+00        0.0   
max            0.0  4.999893e+06  4.999893e+06  9.998126e+06        0.0   

           Idle Max      Idle Min         label  
count  6.783400e+04  6.783400e+04  67834.000000  
mean   3.085054e+05  3.085054e+05      0.118584  
std    1.453953e+06  1.453953e+06      0.323300  
min    0.000000e+00  0.000000e+00      0.000000  
25%    0.000000e+00  0.000000e+00      0.000000  
50%    0.000000e+00  0.000000e+00      0.000000  
75%    0.000000e+00  0.000000e+00      0.000000  
max    9.998126e+06  9.998126e+06      1.000000  

[8 rows x 29 columns]

In [15]:
features_all = [c for c in df.columns if c not in ['label']]

features = [c for c in df.columns if c not in
            ['Source IP',
             ' Source Port',
             ' Destination IP',
             ' Destination Port',
             ' Protocol',
             'label']]
features

[' Flow Duration',
 ' Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min']

In [16]:
X = np.array(df[features])
X_all = np.array(df[features_all])
y = np.array(df.label)
print(X.shape, np.mean(y))

(67834, 23) 0.1185836011439691


# XGBoost algorithm 

https://machinelearningmastery.com/gentle-introduction-xgboost-applied-machine-learning/

In [17]:

import xgboost
from sklearn import model_selection, metrics 



# Resource - https://www.geeksforgeeks.org/sklearn-stratifiedshufflesplit-function-in-python/


# Create object of StratifiedShuffleSplit Class.
#20% holdout validation set
splitter = model_selection.StratifiedShuffleSplit(                  
    n_splits=1,
    test_size=0.2,
    random_state=0)

#Call the instance and split the data frame into training sample and testing sample
for train_index, test_index in splitter.split(X, y):                
    X_train, X_holdout = X[train_index], X[test_index]
    X_train_all, X_holdout_all = X_all[train_index], X_all[test_index]
    y_train, y_holdout = y[train_index], y[test_index]

print(X_train.shape, X_holdout.shape)

(54267, 23) (13567, 23)


In [18]:
#df['label'].value_counts()

In [19]:
#non-tuned XGBoost
model = xgboost.XGBClassifier(seed=0)
print(model)

# use 5-fold stratified cross-validation for parameter tuning
skf = model_selection.StratifiedKFold(                              
    n_splits=5,
    shuffle=True,
    random_state=0)

for i, (train_index, test_index) in enumerate(skf.split(X_train, y_train)):
    X_train_fold, X_test_fold = X_train[train_index], X_train[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    model.fit(X_train_fold, y_train_fold)
    probas = model.predict_proba(X_test_fold)[:,1]
    preds = (probas > 0.5).astype(int)

    print("-"*60)
    print("Fold: %d (%s/%s)" %(i, X_train_fold.shape, X_test_fold.shape))
    print(metrics.classification_report(y_test_fold, preds, target_names=["nonTOR", "TOR"]))
    print("Confusion Matrix: \n%s\n"%metrics.confusion_matrix(y_test_fold, preds))
    print("Log loss : %f" % (metrics.log_loss(y_test_fold, probas)))
    print("AUC      : %f" % (metrics.roc_auc_score(y_test_fold, probas)))
    print("Accuracy : %f" % (metrics.accuracy_score(y_test_fold, preds)))
    print("Precision: %f" % (metrics.precision_score(y_test_fold, preds)))
    print("Recall   : %f" % (metrics.recall_score(y_test_fold, preds)))
    print("F1-score : %f" % (metrics.f1_score(y_test_fold, preds)))

XGBClassifier(base_score=None, booster=None, colsample_bylevel=None,
              colsample_bynode=None, colsample_bytree=None, gamma=None,
              gpu_id=None, importance_type='gain', interaction_constraints=None,
              learning_rate=None, max_delta_step=None, max_depth=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              random_state=None, reg_alpha=None, reg_lambda=None,
              scale_pos_weight=None, seed=0, subsample=None, tree_method=None,
              validate_parameters=None, verbosity=None)
[10:15:33] WARNING: ..\src\learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Admin\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


------------------------------------------------------------
Fold: 0 ((43413, 23)/(10854, 23))
              precision    recall  f1-score   support

      nonTOR       0.99      0.99      0.99      9567
         TOR       0.96      0.96      0.96      1287

    accuracy                           0.99     10854
   macro avg       0.98      0.98      0.98     10854
weighted avg       0.99      0.99      0.99     10854

Confusion Matrix: 
[[9512   55]
 [  55 1232]]

Log loss : 0.028973
AUC      : 0.998376
Accuracy : 0.989865
Precision: 0.957265
Recall   : 0.957265
F1-score : 0.957265
[10:15:37] WARNING: ..\src\learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Admin\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


------------------------------------------------------------
Fold: 1 ((43413, 23)/(10854, 23))
              precision    recall  f1-score   support

      nonTOR       0.99      0.99      0.99      9567
         TOR       0.96      0.95      0.95      1287

    accuracy                           0.99     10854
   macro avg       0.98      0.97      0.97     10854
weighted avg       0.99      0.99      0.99     10854

Confusion Matrix: 
[[9516   51]
 [  65 1222]]

Log loss : 0.030157
AUC      : 0.998595
Accuracy : 0.989313
Precision: 0.959937
Recall   : 0.949495
F1-score : 0.954688
[10:15:41] WARNING: ..\src\learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Admin\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


------------------------------------------------------------
Fold: 2 ((43414, 23)/(10853, 23))
              precision    recall  f1-score   support

      nonTOR       0.99      1.00      0.99      9566
         TOR       0.96      0.95      0.96      1287

    accuracy                           0.99     10853
   macro avg       0.98      0.97      0.97     10853
weighted avg       0.99      0.99      0.99     10853

Confusion Matrix: 
[[9520   46]
 [  67 1220]]

Log loss : 0.029076
AUC      : 0.998204
Accuracy : 0.989588
Precision: 0.963665
Recall   : 0.947941
F1-score : 0.955738
[10:15:45] WARNING: ..\src\learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Admin\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


------------------------------------------------------------
Fold: 3 ((43414, 23)/(10853, 23))
              precision    recall  f1-score   support

      nonTOR       0.99      1.00      0.99      9566
         TOR       0.96      0.95      0.96      1287

    accuracy                           0.99     10853
   macro avg       0.98      0.98      0.98     10853
weighted avg       0.99      0.99      0.99     10853

Confusion Matrix: 
[[9521   45]
 [  58 1229]]

Log loss : 0.027187
AUC      : 0.998796
Accuracy : 0.990510
Precision: 0.964678
Recall   : 0.954934
F1-score : 0.959781
[10:15:49] WARNING: ..\src\learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Admin\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


------------------------------------------------------------
Fold: 4 ((43414, 23)/(10853, 23))
              precision    recall  f1-score   support

      nonTOR       1.00      1.00      1.00      9566
         TOR       0.97      0.97      0.97      1287

    accuracy                           0.99     10853
   macro avg       0.98      0.98      0.98     10853
weighted avg       0.99      0.99      0.99     10853

Confusion Matrix: 
[[9528   38]
 [  44 1243]]

Log loss : 0.025109
AUC      : 0.998715
Accuracy : 0.992444
Precision: 0.970336
Recall   : 0.965812
F1-score : 0.968069


In [20]:
model.fit(X_train, y_train)
probas = model.predict_proba(X_holdout)[:,1]
preds = (probas > 0.5).astype(int)

print(metrics.classification_report(y_holdout, preds, target_names=["nonTOR", "TOR"]))
print("Confusion Matrix: \n%s\n"%metrics.confusion_matrix(y_holdout, preds))
print("Log loss : %f" % (metrics.log_loss(y_holdout, probas)))
print("AUC      : %f" % (metrics.roc_auc_score(y_holdout, probas)))
print("Accuracy : %f" % (metrics.accuracy_score(y_holdout, preds)))
print("Precision: %f" % (metrics.precision_score(y_holdout, preds)))
print("Recall   : %f" % (metrics.recall_score(y_holdout, preds)))
print("F1-score : %f" % (metrics.f1_score(y_holdout, preds)))

[10:15:53] WARNING: ..\src\learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\Admin\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)



              precision    recall  f1-score   support

      nonTOR       1.00      1.00      1.00     11958
         TOR       0.97      0.96      0.97      1609

    accuracy                           0.99     13567
   macro avg       0.98      0.98      0.98     13567
weighted avg       0.99      0.99      0.99     13567

Confusion Matrix: 
[[11909    49]
 [   58  1551]]

Log loss : 0.022419
AUC      : 0.999222
Accuracy : 0.992113
Precision: 0.969375
Recall   : 0.963953
F1-score : 0.966656


# References 
https://kepler-mapper.scikit-tda.org/en/latest/notebooks/TOR-XGB-TDA.html

https://www.geeksforgeeks.org/sklearn-stratifiedshufflesplit-function-in-python/